### ISSUE TITLE
Error while initializing Rayleigh Fit with v4.6

### ISSUE THREAD

**Issue by aHafiz11** [nikolaos-siomos/ATLAS#12]
Hi @nikolaos-siomos ,

I encounter another error while trying to run the new version of ATLAS.

-----------------------------------------
Initializing the Rayleigh Fit...
-----------------------------------------
-- channel: 0355xpar
Traceback (most recent call last):
  File "C:\Users\afwan\OneDrive\GitHub\ATLAS\__master__.py", line 61, in <module>
    processing_chain.ray_test(mst_cfg = mst_cfg,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afwan\OneDrive\GitHub\ATLAS\helper_functions\processing_chain.py", line 388, in ray_test
    __rayleigh_fit__(ray_args, __version__)
  File "C:\Users\afwan\OneDrive\GitHub\ATLAS\visualizer\__rayleigh_fit__.py", line 164, in main
    fpath = make_plot.rayleigh(dir_out = args['output_folder'],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afwan\OneDrive\GitHub\ATLAS\visualizer\plotting\make_plot.py", line 268, in rayleigh
    run(["magick", "convert", fpath, "-posterize", "8", fpath])
  File "C:\Users\afwan\miniconda3\envs\my_env\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afwan\miniconda3\envs\my_env\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\afwan\miniconda3\envs\my_env\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
(my_env) PS C:\Users\afwan\OneDrive\GitHub\ATLAS>

I am not sure which file the error referring to.

**Comment by nikolaos-siomos** [comment]
Hi @aHafiz11,
this is probably an error having to do with imagemagick. Could you try the new version 0.4.7. You will probably not experience this problem anymore
Best
