### ISSUE TITLE
Error in v0.4.1

### ISSUE THREAD

**Issue by cavalpe** [nikolaos-siomos/ATLAS#4]
-----------------------------------------
Start reading Rayleigh signals...
-----------------------------------------
-- Folder contains 59 file(s)!
Reading Rayleigh signals complete!
-----------------------------------------

Traceback (most recent call last):
  File "c:\ATLAS\__master__.py", line 44, in <module>
    cnv_files = processing_chain.converter(mst_args = mst_args,
  File "c:\ATLAS\helper_functions\processing_chain.py", line 81, in converter
    files = __scc_converter__(cnv_ray_args, __version__ = __version__)
  File "c:\ATLAS\scc_converter\__scc_converter__.py", line 48, in main
    nc_fname = processors[mtype](args, version = __version__)
  File "c:\ATLAS\scc_converter\tools\process.py", line 59, in rayleigh
    cfg = modify.fill_defaults(cfg)
  File "c:\ATLAS\scc_converter\tools\modify.py", line 154, in fill_defaults
    (cfg.channels.loc[:,'detected_wavelength'] >= 340.) & \
  File "C:\Users\pcatalan\anaconda3\envs\atlas_box\lib\site-packages\pandas\core\ops\common.py", line 72, in new_method
    return method(self, other)
  File "C:\Users\pcatalan\anaconda3\envs\atlas_box\lib\site-packages\pandas\core\arraylike.py", line 62, in __ge__
    return self._cmp_method(other, operator.ge)
  File "C:\Users\pcatalan\anaconda3\envs\atlas_box\lib\site-packages\pandas\core\series.py", line 6243, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "C:\Users\pcatalan\anaconda3\envs\atlas_box\lib\site-packages\pandas\core\ops\array_ops.py", line 287, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "C:\Users\pcatalan\anaconda3\envs\atlas_box\lib\site-packages\pandas\core\ops\array_ops.py", line 75, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas\_libs\ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'float'

**Comment by aHafiz11** [comment]
Hi @cavalpe @nikolaos-siomos ,

I also encounter the same errors while trying ATLAS with the new version 0.4.1:
![image](https://github.com/nikolaos-siomos/ATLAS/assets/87298036/63332c42-be2a-49e8-862d-72b44ea58b83)

**Comment by nikolaos-siomos** [comment]
Hi all,
there were multiple variable type issues in v0.4.1. They should be fixed in v0.4.2 (now available). Please give it a try and let me know so that we can close the issue. You can have a look at the changelog to see what has changed.
Best

**Comment by nikolaos-siomos** [comment]
I will close this issue assuming it was fixed by version 0.4.3
